ALTER TABLE [dbo].[tblEmployee]
ADD
[ValidFrom] DATETIME2(2) GENERATED ALWAYS AS ROW START CONSTRAINT def_ValidFrom DEFAULT SYSUTCDATETIME(),
[ValidTo] DATETIME2(2) GENERATED ALWAYS AS ROW END CONSTRAINT def_ValidTo DEFAULT CONVERT(datetime2(2), '999-12-31 23:59:59'),
PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)

ALTER TABLE [dbo].[tblEmployee]
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.tblEmployeeHistory))